CREATE TABLE BANK (
    BANK_ID uuid not null,
    BANK_TITLE varchar(255),
    PRIMARY KEY (BANK_ID)
);

CREATE TABLE CLIENT (
    CLIENT_ID uuid not null,
    CLIENT_EMAIL varchar(255),
    CLIENT_FIO varchar(255),
    CLIENT_PASSPORT_NUMBER varchar(205),
    CLIENT_PHONE_NUMBER varchar(205),
    PRIMARY KEY (CLIENT_ID),
    BANK_ID uuid
    CONSTRAINT FK_CLIENT_BANK_ID REFERENCES BANK(BANK_ID)
);

create table CREDIT (
    CREDIT_ID uuid not null,
    CREDIT_LIMIT numeric(19, 2),
    CREDIT_PERCENT numeric(19, 2),
    CREDIT_TITLE varchar(255),
    PRIMARY KEY (CREDIT_ID),
    BANK_ID uuid
    CONSTRAINT FK_CREDIT_BANK_ID REFERENCES BANK(BANK_ID)
);

create table CREDIT_OFFER (
    CREDIT_OFFER_ID uuid not null,
    CREDIT_OFFER_AMOUNT numeric(19, 2),
    CREDIT_OFFER_FIRST_PAY numeric(19, 2),
    CREDIT_OFFER_NAMED varchar(255),
    CREDIT_OFFER_PERCENT_SUM numeric(19, 2),
    CREDIT_OFFER_PERIOD_IN_MONTHS integer,
    PRIMARY KEY (CREDIT_OFFER_ID),
    BANK_ID uuid
    CONSTRAINT FK_CREDIT_OFFER_BANK_ID REFERENCES BANK(BANK_ID),
    CLIENT_ID uuid
    CONSTRAINT FK_CREDIT_OFFER_CLIENT_ID REFERENCES CLIENT(CLIENT_ID),
    CREDIT_ID uuid
    CONSTRAINT FK_CREDIT_OFFER_CREDIT_ID REFERENCES CREDIT(CREDIT_ID)
);

create table PAYMENT_SCHEDULE (
    PAYMENT_SCHEDULE_ID uuid not null,
    PAYMENT_SCHEDULE_AMOUNT_OF_THE_BODY numeric(19, 2),
    PAYMENT_SCHEDULE_AMOUNT_OF_THE_PERCENT numeric(19, 2),
    PAYMENT_SCHEDULE_PAYMENT_AMOUNT numeric(19, 2),
    PAYMENT_SCHEDULE_PAYMENT_DATE date,
    PAYMENT_SCHEDULE_REMAINS numeric(19, 2),
    PRIMARY KEY (PAYMENT_SCHEDULE_ID),
    CREDIT_OFFER_ID uuid
    CONSTRAINT FK_CREDIT_OFFER_ID REFERENCES CREDIT_OFFER(CREDIT_OFFER_ID)
);

